name: Deploy SA360 Custom Column Connector
# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [custom-columns]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fivetran-connector-sdk

      - name: Create configuration.json
        working-directory: "./sa360-custom-columns"
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_LOGIN_CUSTOMER_ID: ${{ secrets.GOOGLE_LOGIN_CUSTOMER_ID }}
        run: |
          echo "Creating config.json with provided secrets..."
          cat <<EOF > configuration.json
          {
            "google_client_id": "$GOOGLE_CLIENT_ID",
            "google_client_secret": "$GOOGLE_CLIENT_SECRET",
            "google_refresh_token": "$GOOGLE_REFRESH_TOKEN",
            "google_login_customer_id": "$GOOGLE_LOGIN_CUSTOMER_ID"
          }
          EOF

      - name: Deploy to fivetran
        working-directory: "./sa360-custom-columns"
        env:
          FIVETRAN_API_KEY: ${{ secrets.FIVETRAN_API_KEY }} # Expose the secret as an environment variable
          FIVETRAN_DESTINATION: ${{ secrets.FIVETRAN_UAT_DESTINATION }} # Expose the secret as an environment variable
        run: |
          ls
          fivetran deploy --api-key $FIVETRAN_API_KEY --destination $FIVETRAN_DESTINATION --configuration ./configuration.json --connection sa360_custom_columns --force
